global:
  image:
    # -- if set it will overwrite all registry entries
    registry:
    # -- if set it will overwrite all pullPolicy
    pullPolicy:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

service:
  call:
    replicaCount: 1
    image:
      registry: ghcr.io
      repository: element-hq/element-call
      pullPolicy: IfNotPresent
      # -- Overrides the image tag whose default is the chart appVersion.
      tag:
    config: {}
    ingress:
      host:
    networkPolicy:
      enabled: false
      ingress:
        # -- ingress for http port (e.g. ingress-controller)
        http: []
      egress:
        # -- activate egress no networkpolicy
        enabled: true
        # -- egress rules
        extra: []
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
    resources: {}
    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Automatically mount a ServiceAccount's API credentials?
      automount: true
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""

    podAnnotations: {}
    podLabels: {}

    podSecurityContext: {}
      # fsGroup: 2000

    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    nodeSelector: {}
    tolerations: []
    affinity: {}

  lkJWT:
    enabled: true
    replicaCount: 1
    image:
      registry: ghcr.io
      repository: element-hq/lk-jwt-service
      pullPolicy: IfNotPresent
      tag: sha-4a29504
    config:
      url: ""
      key: "devkey"
      secret: "secret"
    ingress:
      host:
    networkPolicy:
      enabled: false
      ingress:
        # -- ingress for http port (e.g. ingress-controller)
        http: []
      egress:
        # -- activate egress no networkpolicy
        enabled: false
        # -- egress rules
        extra: []
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
    readinessProbe:
      httpGet:
        path: /healthz
        port: http
    resources: {}
    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Automatically mount a ServiceAccount's API credentials?
      automount: true
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""

    podAnnotations: {}
    podLabels: {}

    podSecurityContext: {}
      # fsGroup: 2000

    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    nodeSelector: {}
    tolerations: []
    affinity: {}
