---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config
  labels:
    app: coturn
data:
  turnserver.conf: |
    server-name={{ .Values.serverName }}
    realm={{ .Values.serverName }}
    static-auth-secret={{ .Values.sharedSecret }}
    use-auth-secret
    cli-password={{ .Values.cliPassword }}
    psql-userdb="host=coturn-pgbouncer dbname={{ .Values.postgres.dbname }} user={{ .Values.postgres.user }} password={{ .Values.postgres.password }} connect_timeout=30"
    cert=/etc/tls/tls.crt
    pkey=/etc/tls/tls.key
    no-loopback-peers
    no-multicast-peers
    verbose
