---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn-pgbouncer
  labels:
    app: coturn-pgbouncer
spec:
  replicas: {{ .Values.pgbouncer.replicas }}
  selector:
    matchLabels:
      app: coturn-pgbouncer
  template:
    metadata:
      labels:
        app: coturn-pgbouncer
    spec:
      containers:
      - name: pgbouncer
        mage: {{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}
        imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy }}
        resources:
          {{ toYaml .Values.pgbouncer.resources | nindent 10 }}
        env:
          - name: PGBOUNCER_PORT
            value: "5432"
          - name: POSTGRESQL_HOST
            value: {{ .Values.postgres.host | quote }}
          - name: PGBOUNCER_DATABASE
            value: {{ .Values.postgres.dbname | quote }}
          - name: POSTGRESQL_USERNAME
            value: {{ .Values.postgres.user | quote }}
          - name: POSTGRESQL_PASSWORD
            value: {{ .Values.postgres.password | quote }}
          - name: PGBOUNCER_AUTH_TYPE
            value: {{ .Values.pgbouncer.authType | quote }}
          - name: PGBOUNCER_MAX_CLIENT_CONN
            value: {{ .Values.pgbouncer.maxClientConn | quote }}
          - name: PGBOUNCER_DEFAULT_POOL_SIZE
            value: {{ .Values.pgbouncer.poolSize | quote }}
          - name: PGBOUNCER_POOL_MODE
            value: {{ .Values.pgbouncer.poolMode | quote }}
        ports:
          - containerPort: 5432
            name: pgbouncer
            protocol: TCP
      {{- if .Values.pgbouncer.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.pgbouncer.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.pgbouncer.tolerations }}
      tolerations:
        {{ toYaml .Values.pgbouncer.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.pgbouncer.affinity }}
      affinity:
        {{ toYaml .Values.pgbouncer.affinity | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
