---
apiVersion: v1
kind: Service
metadata:
  name: coturn
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
spec:
  selector:
    app: coturn
  ports:
  - name: tcp
    port: 3478
    targetPort: 3478
  - name: tls
    port: 5349
    targetPort: 5349
  type: LoadBalancer
