{{- if .Values.service.lkJWT.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "element-call.fullname" . }}-lk-jwt
  labels:
    {{- include "element-call.labels" . | nindent 4 }}
data:
  {{- with .Values.service.lkJWT.config }}
  LIVEKIT_KEY: {{ .key | b64enc }}
  LIVEKIT_SECRET: {{ .secret | b64enc }}
  {{- end }}
{{- end }}
