{{- if .Values.service.lkJWT.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "element-call.fullname" . }}-lk-jwt
  labels:
    {{- include "element-call.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "element-call.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: lk-jwt
{{- end }}
