apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  mas-database.yaml: |
    database:
      connect_timeout: 30
      database: {{ .Values.configs.mas.db_name }}
      host: {{ .Values.configs.mas.db_host }}
      idle_timeout: 600
      max_connections: 10
      max_lifetime: 1800
      min_connections: 0
      password: {{ .Values.configs.mas.db_pass }}
      port: {{ .Values.configs.mas.db_port }}
      username: mas_user

  keycloak_matrix_sync.conf: |
    {{- range $k, $v := .Values.configs.sync }}
    {{ $k }}={{ $v | toString }}
    {{- end }}    
