---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-config
  labels:
    app: ldap
data:
  haproxy.cfg: |
    global
      #debug

    listen ipa
      bind 0.0.0.0:389
      mode tcp
      balance roundrobin
      {{- if .Values.servers }}
      {{- range .Values.servers }}
      {{ . }}
      {{- end }}
      {{- end }}
