---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
spec:
  selector:
    app: ldap
  ports:
  - name: tcp
    port: 389
    targetPort: 389
