---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: ldap
  ports:
  - name: tcp
    port: 389
    targetPort: 389
