---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: webhook
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
        args: ["-vvvvvvvvvvvvvvvvvvvvv"]
        env:
        - name: MATRIX_URL
          value: "https://{{ .Values.ingress.host }}"
        - name: MATRIX_ID
          value: "{{ .Values.matrix.id }}"
        {{- if .Values.matrix.password }}
        - name: MATRIX_PW
          value: "{{ .Values.matrix.password }}"
        {{- end }}
        - name: API_KEY
          value: "{{ .Values.matrix.apiKey }}"
        {{- if .Values.matrix.token }}
        - name: MATRIX_TOKEN
          value: "{{ .Values.matrix.token }}"
        {{- end }}
        ports:
          - containerPort: 4785
            name: webhook
            protocol: TCP
      terminationGracePeriodSeconds: 10
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
