---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
spec:
  selector:
    app: webhook
  ports:
  - name: webhook
    port: 80
    targetPort: 4785
