---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: webhook
    port: 80
    targetPort: 4785
