replicas: 1
image:
  repository: "zerodotfive/matrix-webhook"
  tag: "rawjson"
  pullPolicy: IfNotPresent
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
#integration parameters
matrix:
  id: ""
  password: ""
  apiKey: ""
ingress:
  host: ""
