name: webhook
replicas: 1
image:
  repository: "ghcr.io/code-tool/matrix-stack/webhook"
  tag: "0.0.2"
  pullPolicy: IfNotPresent
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
#integration parameters
matrix:
  id: ""
  password: ""
  apiKey: ""
  token: ""
ingress:
  host: ""
  secretName: ""
  ingressClassName: nginx
  path: "/webhook/(.*)"
