replicas: 1
image:
  repository: "zerodotfive/matrix-webhook"
  tag: "rawjson"
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 1Gi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 2
nodeSelector: {}
tolerations: []
affinity: {}
#integration parameters
matrix:
  id: ""
  password: ""
  apiKey: ""
ingress:
  host: ""
