{{- if .Values.exporter.enabled }}
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: http
  jobLabel: redis-exporter
  selector:
    matchLabels:
      app: redis
---
{{- end }}
