---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    {{- if .Values.exporter.enabled }}
    - name: redis-exporter
      port: 9121
      targetPort: redis-exporter
    {{- end }}
  selector:
    app: redis
