---
apiVersion: v1
kind: Secret
metadata:
  name: livekit-jwt
  labels:
    {{- include "livekit-jwt.selectorLabels" . | nindent 4 }}
data:
  LIVEKIT_KEY: {{ .Values.config.key | b64enc }}
  LIVEKIT_SECRET: {{ .Values.config.secret | b64enc }}
