---
apiVersion: v1
kind: Service
metadata:
  name: livekit-jwt
  labels:
    {{- include "livekit-jwt.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "livekit-jwt.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
