{{- if .Values.admin.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse-admin
  {{- if or .Values.admin.ingress.annotations .Values.admin.ingress.commonAnnotations }}
  {{ $annotations := merge .Values.admin.ingress.annotations .Values.admin.ingress.commonAnnotations }}
  annotations: {{ toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.admin.ingress.serverName }}
      {{- if .Values.admin.ingress.secretName }}
      secretName: {{ .Values.admin.ingress.secretName }}
      {{- end }}
  rules:
    - host: {{ .Values.admin.ingress.serverName }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin
                port:
                  number: 80
{{- end }}
