---
apiVersion: v1
kind: Service
metadata:
  name: admin
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
spec:
  selector:
    app: admin
  ports:
  - name: admin
    port: 80
    targetPort: 80
