{{- if .Values.admin.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse-admin
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.admin.ingress.serverName }}
      {{- if .Values.admin.ingress.secretName }}
      secretName: {{ .Values.admin.ingress.secretName }}
      {{- end }}
  rules:
    - host: {{ .Values.admin.ingress.serverName }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin
                port:
                  number: 80
{{- end }}
