---
apiVersion: v1
kind: Service
metadata:
  name:  synapse-client-reader-envoy
  labels:
    {{- include "synapse-client-reader-envoy.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.envoyProxy.service.type }}
  ports:
    - port: {{ .Values.envoyProxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.envoyProxy.admin.port }}
      targetPort: http-admin
      protocol: TCP
      name: http-admin
  selector:
    {{- include "synapse-client-reader-envoy.selectorLabels" . | nindent 4 }}
