apiVersion: v1
kind: Secret
metadata:
  name: matrix-authentication
  labels:
    {{- include "matrix-authentication.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  mas-config.yaml: |-
    {{- if or .Values.matrixAuthentication.config.clients .Values.experimentalFeatures.msc3967.enabled }}
    {{- $msc3861 := dict "client_id" .Values.experimentalFeatures.msc3861.client_id "client_auth_method" .Values.experimentalFeatures.msc3861.client_auth_method "client_secret" .Values.experimentalFeatures.msc3861.client_secret }}
    {{- $clients := append .Values.matrixAuthentication.config.clients $msc3861  }}
    clients:
      {{ toYaml $clients | nindent 6 }}
    {{- end }}
    http:
      listeners:
        - name: http
          resources:
            - name: discovery
            - name: human
            - name: oauth
            - name: compat
            - name: graphql
              playground: false
            - name: assets
              path: /usr/local/share/mas-cli/assets/
          binds:
            - address: '[::]:8080'
          proxy_protocol: false
        - name: internal
          resources:
            - name: health
          binds:
            - address: '[::]:8081'
        - name: metrics
          resources:
            - name: prometheus
          binds:
            - address: '[::]:9100'
      trusted_proxies: []
      public_base: {{ printf "https://%s/" .Values.matrixAuthentication.ingress.host }}
      issuer: {{ printf "https://%s/" .Values.matrixAuthentication.ingress.host }}
    database:
      {{ toYaml .Values.matrixAuthentication.config.database | nindent 6 }}
    {{- if .Values.matrixAuthentication.config.secrets }}
    secrets:
      {{ toYaml .Values.matrixAuthentication.config.secrets | nindent 6 }}
    {{- end }}
    {{- if .Values.matrixAuthentication.config.secrets }}
    passwords:
      {{ toYaml .Values.matrixAuthentication.config.passwords | nindent 6 }}
    {{- end }}
    matrix:
      homeserver: {{ .Values.synapse.serverName }}
      secret: {{ .Values.experimentalFeatures.msc3861.admin_token }}
      endpoint: {{ printf "https://%s/" .Values.synapse.serverName }}
    {{- if or .Values.matrixAuthentication.config.upstream_oauth2.google .Values.matrixAuthentication.config.upstream_oauth2.providers }}
    providers:
    {{- range $g := .Values.matrixAuthentication.config.upstream_oauth2.google }}
      - id: {{ $g.id }}
        client_id: {{ $g.client_id | quote }}
        client_secret: {{ $g.client_secret | quote }}
        human_name: Google
        brand_name: "google"
        issuer: "https://accounts.google.com"
        scope: "openid profile email"
        token_endpoint_auth_method: client_secret_post
        claims_imports:
          localpart:
            action: require
            template: "{{`{{ (user.email | split('@'))[0] }}`}}"
          displayname:
            action: suggest
            template: "{{`{{ (user.email | split('@'))[0] }}`}}"
          email:
            action: require
            template: "{{`{{ user.email }}`}}"
    {{- end }}
    {{- if .Values.matrixAuthentication.config.upstream_oauth2.providers }}
    {{ toYaml .Values.matrixAuthentication.config.upstream_oauth2.providers | nindent 6 }}
    {{- end }}
    {{- end }}
    {{ .Values.matrixAuthentication.configYaml | nindent 4 }}
