{{- if .Values.matrixAuthentication.enabled }}
{{- if .Values.matrixAuthentication.podDisruptionBudget.ebabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: matrix-authentication
spec:
  {{- if and .Values.matrixAuthentication.podDisruptionBudget.minAvailable (not (hasKey .Values.matrixAuthentication.podDisruptionBudget "maxUnavailable")) }}
  minAvailable: {{ .Values.matrixAuthentication.podDisruptionBudget.minAvailable }}
  {{- else if .Values.matrixAuthentication.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.matrixAuthentication.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "matrix-authentication.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
