{{- if .Values.slidingSyncProxy.autoscaling.enabled }}
---
{{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: sliding-sync-proxy
  labels:
    {{- include "sliding-sync-proxy.selectorLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sliding-sync-proxy
  minReplicas: {{ .Values.slidingSyncProxy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.slidingSyncProxy.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.slidingSyncProxy.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.slidingSyncProxy.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.slidingSyncProxy.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.slidingSyncProxy.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
