{{- if .Values.slidingSyncProxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: sliding-sync-proxy
  labels:
    {{- include "sliding-sync-proxy.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.slidingSyncProxy.service.type }}
  ports:
    - port: {{ .Values.slidingSyncProxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sliding-sync-proxy.selectorLabels" . | nindent 4 }}
{{- end }}
