{{- if .Values.slidingSyncProxy.enabled }}
{{- if .Values.slidingSyncProxy.podDisruptionBudget.ebabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sliding-sync-proxy
spec:
  {{- if and .Values.slidingSyncProxy.podDisruptionBudget.minAvailable (not (hasKey .Values.slidingSyncProxy.podDisruptionBudget "maxUnavailable")) }}
  minAvailable: {{ .Values.slidingSyncProxy.podDisruptionBudget.minAvailable }}
  {{- else if .Values.slidingSyncProxy.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.slidingSyncProxy.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sliding-sync-proxy.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
