{{- if .Values.slidingSyncProxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sliding-sync-proxy
  labels:
    {{- include "sliding-sync-proxy.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.slidingSyncProxy.autoscaling.enabled }}
  replicas: {{ .Values.slidingSyncProxy.replicaCount }}
  {{- end }}
  {{- if .Values.slidingSyncProxy.updateStrategy }}
  strategy:
    {{ toYaml .Values.slidingSyncProxy.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sliding-sync-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.slidingSyncProxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sliding-sync-proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: sliding-sync-proxy
          image: {{ .Values.slidingSyncProxy.image.repository }}:{{ .Values.slidingSyncProxy.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: SYNCV3_BINDADDR
              value: "0.0.0.0:8008"
            - name: SYNCV3_DB
              value: {{ .Values.slidingSyncProxy.env.SYNCV3_DB | quote }}
            - name: SYNCV3_SERVER
              value: {{ .Values.slidingSyncProxy.env.SYNCV3_SERVER | quote }}
            - name: SYNCV3_SECRET
              value: {{ .Values.slidingSyncProxy.env.SYNCV3_SECRET | quote }}
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.slidingSyncProxy.resources | nindent 12 }}
      {{- if .Values.slidingSyncProxy.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.slidingSyncProxy.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.slidingSyncProxy.tolerations }}
      tolerations:
        {{ toYaml .Values.slidingSyncProxy.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.slidingSyncProxy.affinity }}
      affinity:
        {{ toYaml .Values.slidingSyncProxy.affinity | nindent 8 }}
      {{- end }}
{{- end }}
