{{- if .Values.slidingSyncProxy.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sliding-sync-proxy
  annotations:
    nginx.org/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/server-snippet: |
      # dummy
      {{- if .Values.root_redirect_url }}
      location ~ ^/$ {
         rewrite / {{ .Values.root_redirect_url }} permanent;
      }
      {{ end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.slidingSyncProxy.ingress.host }}
      {{- if .Values.slidingSyncProxy.ingress.secretName }}
      secretName: {{ .Values.slidingSyncProxy.ingress.secretName }}
      {{- end }}
  rules:
  - host: {{ .Values.slidingSyncProxy.ingress.host }}
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            port:
              number: 80
            name: sliding-sync-proxy
{{- end }}
