{{- range $worker, $options := .Values.synapse.autoscalingWorkers }}
{{- if $options.autoscaling.enabled }}
{{- $name := $worker | replace "_" "-"}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: synapse-{{ $name }}-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synapse-{{ $name }}
  minReplicas: {{ $options.autoscaling.minReplicas }}
  maxReplicas: {{ $options.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 15
{{- end }}
{{- end }}
