{{- $workers := merge (deepCopy .Values.synapse.autoscalingWorkers) (deepCopy .Values.synapse.deployScalingWorkers) (deepCopy .Values.synapse.singletonWorkers) -}}
{{- range $worker, $count := $workers }}
{{ $name := $worker | replace "_" "-" }}
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-{{ $name }}
  {{- with $.Values.synapse.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "synapse-workers.selectorLabels" $name | nindent 4 }}
  ports:
  - name: client
    port: 80
    targetPort: 8008
  - name: http
    port: 8008
    targetPort: 8008
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-client-reader-headless
  {{- with $.Values.synapse.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "synapse-client-reader.selectorLabels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: 8008
      targetPort: 8008
  selector:
    {{- include "synapse-client-reader.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-client-keys-headless
  {{- with $.Values.synapse.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "synapse-client-keys.selectorLabels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: 8008
      targetPort: 8008
  selector:
    {{- include "synapse-client-keys.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-room-headless
  {{- with $.Values.synapse.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "synapse-room.selectorLabels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: 8008
      targetPort: 8008
  selector:
    {{- include "synapse-room.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-sync-headless
  {{- with $.Values.synapse.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "synapse-sync.selectorLabels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: 8008
      targetPort: 8008
  selector:
    {{- include "synapse-sync.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-federation-reader-headless
  {{- with $.Values.synapse.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "synapse-federation-reader.selectorLabels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: 8008
      targetPort: 8008
  selector:
    {{- include "synapse-federation-reader.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-quarantined-media-changes-headless
  {{- with $.Values.synapse.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "synapse-quarantined-media-changes.selectorLabels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http
      port: 8008
      targetPort: 8008
  selector:
    {{- include "synapse-quarantined-media-changes.selectorLabels" . | nindent 6 }}
