{{- if .Values.synapse.deployScalingWorkersPdb.enabled }}
{{/* deployScalingWorkers: replicas>1 → minAvailable:1; replicas=1 → maxUnavailable:1 allows node drain */}}
{{- range $worker, $options := .Values.synapse.deployScalingWorkers }}
{{ $name := $worker | replace "_" "-" }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: synapse-{{ $name }}
spec:
  {{- if gt ($options.replicas | int) 1 }}
  {{- if and $.Values.synapse.deployScalingWorkersPdb.minAvailable (not (hasKey $.Values.synapse.deployScalingWorkersPdb "maxUnavailable")) }}
  minAvailable: {{ $.Values.synapse.deployScalingWorkersPdb.minAvailable }}
  {{- else if $.Values.synapse.deployScalingWorkersPdb.maxUnavailable }}
  maxUnavailable: {{ $.Values.synapse.deployScalingWorkersPdb.maxUnavailable }}
  {{- end }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "synapse-workers.selectorLabels" $name | nindent 6 }}
{{- end }}

{{/* singletonWorkers: replicas=1, maxUnavailable:1 allows node drain */}}
{{- range $worker, $options := .Values.synapse.singletonWorkers }}
{{ $name := $worker | replace "_" "-" }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: synapse-{{ $name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "synapse-workers.selectorLabels" $name | nindent 6 }}
{{- end }}

{{- end }}
