{{- range $worker, $options := .Values.synapse.autoscalingWorkers }}
{{- $name := $worker | replace "_" "-"}}
{{- if and $options.autoscaling.enabled (not $options.kedaAutoscaling.enabled) }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: synapse-{{ $name }}-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synapse-{{ $name }}
  minReplicas: {{ $options.autoscaling.minReplicas }}
  maxReplicas: {{ $options.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 15
{{- end }}
{{- if $options.kedaAutoscaling.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: synapse-{{ $name }}-cron
spec:
  scaleTargetRef:
    name: synapse-{{ $name }}
  minReplicaCount: {{ $options.kedaAutoscaling.minReplicaCount }}
  cooldownPeriod: 300
  triggers:
  - type: cron
    metadata:
      timezone: {{ $options.kedaAutoscaling.timezone | quote }}
      start: {{ $options.kedaAutoscaling.start | quote }}
      end: {{ $options.kedaAutoscaling.end | quote }}
      desiredReplicas: {{ $options.kedaAutoscaling.desiredReplicas | quote }}
{{- end }}
{{- end }}
