{{- if .Values.synapse.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: synapse-metrics
spec:
  selector:
    matchLabels:
      scrapeMetrics9092: 'true'
  podMetricsEndpoints:
  - port: metrics
    path: "/_synapse/metrics"
---
{{- end }}
