{{- range $worker, $options := .Values.synapse.autoscalingWorkers }}
{{- $name := $worker | replace "_" "-"}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-{{ $name }}
  labels:
    {{- include "synapse-workers.selectorLabels" $name | nindent 4 }}
spec:
  {{- if not $options.autoscaling.enabled }}
  replicas: {{ $options.replicas }}
  {{- end }}
  {{- if $.Values.synapse.updateStrategy }}
  strategy:
    {{ toYaml $.Values.synapse.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "synapse-workers.selectorLabels" $name | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "synapse-workers.annotations" $ | nindent 8 }}
      labels:
        {{- include "synapse-workers.selectorLabels" $name | nindent 8 }}
    spec:
      {{ include "synapse-workers.containers" (dict "name" $name "image" $.Values.synapse.image "worker" $worker "options" $options "resourcesDefaults" $.Values.synapse.resourcesDefaults "nodeSelector" $.Values.synapse.nodeSelector "tolerations" $.Values.synapse.tolerations "affinity" $.Values.synapse.affinity) | nindent 6 }}
{{ end }}
