---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: well-known
  {{- if or .Values.wellKnown.ingress.annotations .Values.wellKnown.ingress.commonAnnotations }}
  {{ $annotations := merge .Values.wellKnown.ingress.annotations .Values.wellKnown.ingress.commonAnnotations }}
  annotations: {{ toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.synapse.serverName }}
      {{- if .Values.ingress.secretName }}
      secretName: {{ .Values.ingress.secretName }}
      {{- end }}
  rules:
  - host: {{ .Values.synapse.serverName }}
    http:
      paths:
      - path: /\.well-known/matrix
        pathType: ImplementationSpecific
        backend:
          service:
            port:
              number: 80
            name: well-known
