---
apiVersion: v1
kind: Service
metadata:
  name: well-known
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
spec:
  selector:
    app: well-known
  ports:
  - name: http
    port: 80
    targetPort: 80
