---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: well-known
  labels:
    app: well-known
spec:
  replicas: 1
  selector:
    matchLabels:
      app: well-known
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/well-known-configmap.yaml") $ | sha256sum }}
      labels:
        app: well-known
    spec:
      containers:
      - name: well-known
        image: nginx
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        resources:
          {{- toYaml .Values.wellKnown.resources | nindent 10 }}
        volumeMounts:
        - name: well-known-config
          subPath: default.conf
          mountPath: /etc/nginx/conf.d/default.conf
        - name: well-known-config
          subPath: client
          mountPath: /usr/share/nginx/html/.well-known/matrix/client
        - name: well-known-config
          subPath: server
          mountPath: /usr/share/nginx/html/.well-known/matrix/server
        {{- if .Values.openid_configuration }}
        - name: well-known-config
          subPath: openid-configuration
          mountPath: /usr/share/nginx/html/.well-known/matrix/openid-configuration
        {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.wellKnown.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.wellKnown.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.wellKnown.tolerations }}
      tolerations:
        {{ toYaml .Values.wellKnown.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.wellKnown.affinity }}
      affinity:
        {{ toYaml .Values.wellKnown.affinity | nindent 8 }}
      {{- end }}
      volumes:
      - name: well-known-config
        configMap:
          name: well-known-config
