apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-media-repo.fullname" . }}
  labels:
    {{- include "matrix-media-repo.labels" . | nindent 4 }}
data:
  00-media-repo.yaml: |
    repo:
      bindAddress: '0.0.0.0'
      port: 8000
      logDirectory: '-'
    {{- with .Values.extraRepo }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}

    metrics:
      enabled: true
      bindAddress: '0.0.0.0'
      port: 9000

  01-config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}

{{- range $domain, $config := .Values.homeservers }}
  02-{{ $domain | replace "." "-" }}.yaml: |
    homeserver: {{ $domain }}
    {{- $config | toYaml | nindent 4 }}

{{- end }}
