image:
  repository: "ghcr.io/code-tool/matrix-ldap-sync"
  tag: "0.0.1"
  pullPolicy: IfNotPresent
cronSchedule: "*/20 * * * *"
activeDeadlineSeconds: 1000
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
configs:
  LDAP_URL: ''
  LDAP_BASE: ''
  LDAP_FILTER: ''
  SYNAPSE_HOMESERVER_URL: ''
  DO_REAL_JOB: false
secrets:
  LDAP_BIND_DN: ''
  LDAP_BIND_PASSWD: ''
  SYNAPSE_USER_ID: ''
  SYNAPSE_ACCESS_TOKEN: ''
