apiVersion: batch/v1
kind: CronJob
metadata:
  name: ldap-sync
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  schedule: {{ .Values.cronSchedule | quote }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      backoffLimit: 1
      parallelism: 1
      template:
        metadata:
          labels:
            cronjob: ldap-sync
        spec:
          activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
          restartPolicy: Never
          containers:
            - name: ldap-sync
              image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
              args: [ "sync", "--log-level", "0" ]
              resources:
                {{ toYaml .Values.resources | nindent 16 }}
              envFrom:
                - configMapRef:
                    name: ldap-sync
                - secretRef:
                    name: ldap-sync
          {{- if .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml .Values.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.tolerations }}
          tolerations:
            {{ toYaml .Values.tolerations | nindent 12 }}
          {{- end }}
          {{- if .Values.affinity }}
          affinity:
            {{ toYaml .Values.affinity | nindent 12 }}
          {{- end }}
