---
apiVersion: v1
kind: Service
metadata:
  name: sentry-webhook
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: sentry-webhook
  ports:
  - name: sentry-webhook
    port: 80
    targetPort: {{ .Values.conf.APP_PORT }}
