---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jitsi-web
  {{- if or .Values.ingress.annotations .Values.ingress.commonAnnotations }}
  {{ $annotations := merge .Values.ingress.annotations .Values.ingress.commonAnnotations }}
  annotations: {{ toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.serverName }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: jitsi-web
                port:
                  number: 80
            path: /
          - pathType: ImplementationSpecific
            backend:
              service:
                name: prosody
                port:
                  number: 5280
            path: /xmpp-websocket
          - pathType: ImplementationSpecific
            backend:
              service:
                name: jitsi-jvb
                port:
                  number: 9090
            path: /colibri-ws
  tls:
    - hosts:
        - {{ .Values.ingress.serverName }}
      {{- if .Values.ingress.secretName }}
      secretName: {{ .Values.ingress.secretName }}
      {{- end }}
