apiVersion: v1
kind: Service
metadata:
  labels:
    service: jitsi-jvb
  name: jitsi-jvb
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - name: udp
    port: 30300
    protocol: UDP
    nodePort: 30300
  - name: tcp
    port: 30301
    protocol: TCP
    nodePort: 30301
  - name: http
    port: 9090
    protocol: TCP
    nodePort: 30390
  selector:
    k8s-app: jitsi-jvb
