apiVersion: v1
kind: Service
metadata:
  labels:
    service: prosody
  name: prosody
spec:
  ports:
  - name: "http"
    port: 5280
    targetPort: 5280
  - name: "client"
    port: 5222
    targetPort: 5222
  selector:
    k8s-app: jitsi-prosody
