---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-alertmanager-receiver
  labels:
    app: matrix-alertmanager-receiver
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: matrix-alertmanager-receiver
  template:
    metadata:
      labels:
        app: matrix-alertmanager-receiver
    spec:
      containers:
      - name: matrix-alertmanager-receiver
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
          "--config-path",
          "/etc/matrix-alertmanager-receiver.yaml"
          "--log-level",
          {{ .Values.logLevel | quote }}
        ]
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
        env:
        ports:
          - containerPort: {{ .Values.service.targetPort }}
            name: http
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /etc/matrix-alertmanager-receiver.yaml
            subPath: matrix-alertmanager-receiver.yaml
      terminationGracePeriodSeconds: 10
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: matrix-alertmanager-receiver
