---
apiVersion: v1
kind: Service
metadata:
  name: matrix-alertmanager-receiver
spec:
  selector:
    app: matrix-alertmanager-receiver
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.service.targetPort }}
