image:
  repository: "redis"
  tag: "7.2.4"
  pullPolicy: IfNotPresent
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
exporter:
  enabled: true
  image:
    repository: "oliver006/redis_exporter"
    tag: "v1.59.0"
    pullPolicy: IfNotPresent
