image:
  repository: "redis"
  tag: ''
  pullPolicy: IfNotPresent
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
priorityClassName: ''
exporter:
  enabled: true
  image:
    repository: "oliver006/redis_exporter"
    tag: "v1.93.0"
    pullPolicy: IfNotPresent
