image:
  repository: "haproxy"
  tag: "2.8.24"
  pullPolicy: IfNotPresent
replicas: 1
servers: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
service:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
